# Generated by Django 2.2.1 on 2019-09-28 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('media', models.ImageField(upload_to=social.models.user_directory_path)),
                ('twitter_engagements', models.PositiveIntegerField(default=0)),
                ('instagram_engagements', models.PositiveIntegerField(default=0)),
                ('facebook_engagements', models.PositiveIntegerField(default=0)),
                ('twitter_followers', models.PositiveIntegerField(default=0)),
                ('instagram_followers', models.PositiveIntegerField(default=0)),
                ('facebook_followers', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPostPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_spend', models.FloatField(default=0)),
                ('instagram_spend', models.FloatField(default=0)),
                ('facebook_spend', models.FloatField(default=0)),
                ('twitter_engagements', models.PositiveIntegerField(default=0)),
                ('instagram_engagements', models.PositiveIntegerField(default=0)),
                ('facebook_engagements', models.PositiveIntegerField(default=0)),
                ('twitter_followers', models.PositiveIntegerField(default=0)),
                ('instagram_followers', models.PositiveIntegerField(default=0)),
                ('facebook_followers', models.PositiveIntegerField(default=0)),
                ('social_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.SocialPost')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=500)),
                ('user_count', models.PositiveIntegerField()),
                ('tweet_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
