# Generated by Django 2.2.1 on 2019-10-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='facebook_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='instagram_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='twitter_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialpostpromotion',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
