# Generated by Django 2.2.1 on 2019-10-23 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20191001_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
