# Generated by Django 2.2.1 on 2019-09-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='sent_at',
            field=models.DateField(default='1986-04-22'),
        ),
    ]
