# Generated by Django 2.2.1 on 2019-09-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_directmessage_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
