# Generated by Django 2.2.1 on 2019-09-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_auto_20190928_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='sent_at',
            field=models.DateTimeField(default='1986-04-22 00:00:00'),
        ),
    ]
