# Generated by Django 2.2.1 on 2019-09-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_auto_20190928_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
