# Generated by Django 2.2.1 on 2019-10-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0005_auto_20190929_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('influencer', models.ManyToManyField(to='discover.Influencer')),
            ],
        ),
    ]
